/*
 * Copyright (C) 2023 Yaraku, Inc.
 *
 * This file is part of Human Evaluation Tool.
 *
 * Human Evaluation Tool is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Human Evaluation Tool is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Human Evaluation Tool. If not, see <https://www.gnu.org/licenses/>.
 *
 * AUTO-GENERATED by scripts/gen_categories.py — edit config/categories.txt instead.
 */

export default function ErrorCategorySelector(props) {
  return (
    <select
      className={props.className}
      disabled={props.disabled}
      onChange={props.onChange}
      value={props.value}
    >
      <optgroup>
        <option id="000" value="000">
          No Error
        </option>
      </optgroup>
      <optgroup label="Accuracy">
        <option id="A01" value="A01">
          Mistranslation
        </option>
        <option id="A02" value="A02">
          Positive/Negative
        </option>
        <option id="A03" value="A03">
          Numbers
        </option>
        <option id="A04" value="A04">
          Pronoun
        </option>
        <option id="A05" value="A05">
          Proper Noun
        </option>
        <option id="A06" value="A06">
          Omission
        </option>
        <option id="A07" value="A07">
          Addition
        </option>
        <option id="A08" value="A08">
          Untranslated
        </option>
        <option id="A09" value="A09">
          Others
        </option>
      </optgroup>
      <optgroup label="Fluency">
        <option id="F01" value="F01">
          Typography/Spelling
        </option>
        <option id="F02" value="F02">
          Wrong Kanji
        </option>
        <option id="F03" value="F03">
          Grammar
        </option>
        <option id="F04" value="F04">
          Misuse
        </option>
        <option id="F05" value="F05">
          Collocation
        </option>
        <option id="F06" value="F06">
          Grammar Register
        </option>
        <option id="F07" value="F07">
          Ambiguity
        </option>
        <option id="F08" value="F08">
          Unintelligible
        </option>
        <option id="F09" value="F09">
          Symbols
        </option>
        <option id="F10" value="F10">
          Others
        </option>
      </optgroup>
      <optgroup label="Terminology">
        <option id="T01" value="T01">
          Inconsistent with termbase
        </option>
        <option id="T02" value="T02">
          Inconsistent with domain
        </option>
        <option id="T03" value="T03">
          Inconsistent use
        </option>
        <option id="T04" value="T04">
          Others
        </option>
      </optgroup>
      <optgroup label="Style">
        <option id="S01" value="S01">
          Inconsistent with company style
        </option>
        <option id="S02" value="S02">
          Register
        </option>
        <option id="S03" value="S03">
          Inconsistent style
        </option>
        <option id="S04" value="S04">
          Others
        </option>
      </optgroup>
      <optgroup label="Locale">
        <option id="L01" value="L01">
          Locale convention
        </option>
      </optgroup>
      <optgroup label="SourceError">
        <option id="SE1" value="SE1">
          Source Error
        </option>
      </optgroup>
    </select>
  );
}
