#!/usr/bin/env python3
"""
Generate CATEGORY_NAME in utils.py and ErrorCategorySelector.jsx
from config/categories.txt.

Usage:
    python scripts/gen_categories.py

After running, rebuild the frontend:
    cd frontend && npm run build
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CATEGORIES_FILE = REPO_ROOT / "config" / "categories.txt"
UTILS_FILE = REPO_ROOT / "backend" / "src" / "human_evaluation_tool" / "utils.py"
SELECTOR_FILE = REPO_ROOT / "frontend" / "src" / "components" / "ErrorCategorySelector.jsx"


def parse_categories(text: str) -> list[dict]:
    """
    Parse an indented category file into a flat list of entries.

    Each entry is a dict with keys:
      - id    (str)       e.g. "A01"
      - label (str)       e.g. "Mistranslation"
      - group (str|None)  e.g. "Accuracy", or None for ungrouped items
    """
    entries: list[dict] = []
    current_group: str | None = None

    for line in text.splitlines():
        # strip comments and blank lines
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        stripped = line.lstrip()
        indented = len(line) != len(stripped)

        if not indented:
            if ":" in stripped:
                # ungrouped item, e.g.  "no-error: No Error"
                id_, _, label = stripped.partition(":")
                entries.append({"id": id_.strip(), "label": label.strip(), "group": None})
                current_group = None
            else:
                # group header, e.g.  "Accuracy"
                current_group = stripped.strip()
        else:
            if ":" not in stripped:
                print(f"WARNING: skipping malformed line: {line!r}")
                continue
            id_, _, label = stripped.partition(":")
            entries.append({"id": id_.strip(), "label": label.strip(), "group": current_group})

    return entries


def _category_name_value(entry: dict) -> str:
    if entry["group"]:
        return f"{entry['group']}/{entry['label']}"
    return entry["label"]


def generate_category_name_dict(entries: list[dict]) -> str:
    lines = ["CATEGORY_NAME: Final[dict[str, str]] = {"]
    for e in entries:
        lines.append(f'    "{e["id"]}": "{_category_name_value(e)}",')
    lines.append("}")
    return "\n".join(lines)


def generate_selector_jsx(entries: list[dict]) -> str:
    # Preserve group insertion order
    groups: dict[str | None, list[dict]] = {}
    group_order: list[str | None] = []
    for e in entries:
        g = e["group"]
        if g not in groups:
            groups[g] = []
            group_order.append(g)
        groups[g].append(e)

    lines: list[str] = []

    lines.append("""\
/*
 * Copyright (C) 2023 Yaraku, Inc.
 *
 * This file is part of Human Evaluation Tool.
 *
 * Human Evaluation Tool is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Human Evaluation Tool is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Human Evaluation Tool. If not, see <https://www.gnu.org/licenses/>.
 *
 * AUTO-GENERATED by scripts/gen_categories.py — edit config/categories.txt instead.
 */""")
    lines.append("")
    lines.append("export default function ErrorCategorySelector(props) {")
    lines.append("  return (")
    lines.append("    <select")
    lines.append("      className={props.className}")
    lines.append("      disabled={props.disabled}")
    lines.append("      onChange={props.onChange}")
    lines.append("      value={props.value}")
    lines.append("    >")

    for g in group_order:
        items = groups[g]
        if g is None:
            lines.append("      <optgroup>")
        else:
            lines.append(f'      <optgroup label="{g}">')
        for e in items:
            lines.append(f'        <option id="{e["id"]}" value="{e["id"]}">')
            lines.append(f'          {e["label"]}')
            lines.append(f'        </option>')
        lines.append("      </optgroup>")

    lines.append("    </select>")
    lines.append("  );")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def update_utils_py(entries: list[dict]) -> None:
    content = UTILS_FILE.read_text()
    new_dict = generate_category_name_dict(entries)

    pattern = r'CATEGORY_NAME: Final\[dict\[str, str\]\] = \{[\s\S]*?\}'
    new_content, count = re.subn(pattern, new_dict, content)

    if count == 0:
        print(f"ERROR: CATEGORY_NAME dict not found in {UTILS_FILE}")
        sys.exit(1)

    UTILS_FILE.write_text(new_content)
    print(f"  updated  {UTILS_FILE.relative_to(REPO_ROOT)}")


def update_selector_jsx(entries: list[dict]) -> None:
    SELECTOR_FILE.write_text(generate_selector_jsx(entries))
    print(f"  updated  {SELECTOR_FILE.relative_to(REPO_ROOT)}")


def main() -> None:
    if not CATEGORIES_FILE.exists():
        print(f"ERROR: {CATEGORIES_FILE} not found")
        sys.exit(1)

    entries = parse_categories(CATEGORIES_FILE.read_text())

    if not entries:
        print("ERROR: no categories parsed — check config/categories.txt")
        sys.exit(1)

    print(f"Parsed {len(entries)} categories from {CATEGORIES_FILE.relative_to(REPO_ROOT)}")
    update_utils_py(entries)
    update_selector_jsx(entries)
    print("Done. Rebuild the frontend to apply changes:  cd frontend && npm run build")


if __name__ == "__main__":
    main()
